-- MySQL Script generated by MySQL Workbench
-- Mon Aug 28 14:30:39 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Gen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gen` (
  `GenID` INT NOT NULL,
  `naam` VARCHAR(45) NULL,
  `locatie` VARCHAR(45) NULL,
  `beschrijving` VARCHAR(45) NULL,
  `mutatieID` INT NULL,
  PRIMARY KEY (`GenID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mutatie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mutatie` (
  `mutatieID` INT NOT NULL,
  `Chromosonale locatie` VARCHAR(45) NULL,
  `GenID` INT NULL,
  PRIMARY KEY (`mutatieID`),
  INDEX `GenID_idx` (`GenID` ASC),
  CONSTRAINT `GenID`
    FOREIGN KEY (`GenID`)
    REFERENCES `mydb`.`Gen` (`GenID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`patient` (
  `patientID` INT NOT NULL,
  `naam` VARCHAR(45) NULL,
  `geslacht` ENUM('M', 'V') NULL,
  `leeftijd_diagnose` INT NULL,
  `mutatieID` INT NULL,
  PRIMARY KEY (`patientID`),
  INDEX `mutatieID_idx` (`mutatieID` ASC),
  CONSTRAINT `mutatieID`
    FOREIGN KEY (`mutatieID`)
    REFERENCES `mydb`.`mutatie` (`mutatieID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
